---
title: "Biodiversity Visualizations"
output: html_document
date: "2024-03-31"
---

Load Data

```{r}
library(dplyr)
library(tidyverse)
library(tidyr)
library(knitr)
library(car)

ipak <- function(pkg){
new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("ggplot2", "ggpubr", "rstatix", "dplyr", "ggthemes", "ggformula", "ggpmisc", "GGally", "arm", "ggstatsplot", "readr")
ipak(packages)

select <- dplyr::select

AllVars <- read_csv("./AllVarsPAMSitesandBioRich.csv")
species <- AllVars[, 27:ncol(AllVars)]
species <- species[!grepl("total", names(species), ignore.case = TRUE)]
```

Number of Species at Each Site

```{r}
species_count <- AllVars %>%
  select(site, Total_Species, total_Owls, Total_mammals, total_WP, total_frogs)
```

Total Number of Species

```{r}
# Calculate the sum of selected columns
species_numbers <- as.data.frame(colSums(species))
```

Significant Difference by Division (add box plot)

*Compute ANVOA + Tukey*

```{r}
pwc <- AllVars %>% tukey_hsd(Total_Species ~ division) 
pwc

pwc <- pwc %>% add_xy_position(x = "division")
ggboxplot(fill = "skyblue", color = "blue", AllVars, x = "division", y = "Total_Species") +
  stat_pvalue_manual(pwc, hide.ns = TRUE) +
  labs(title = "Total Species by Division",
       x = "Division",
       y = "Total Species",
       subtitle = get_test_label(res.aov, detailed = TRUE),
       caption = get_pwc_label(pwc)
    ) +
  scale_x_discrete(labels = c("Korstian", "Blackwood", "Durham"))

# make these capital
```

Significant Correlation with trail distance (scatter plot)

```{r}
avPlots.invis <- function(MODEL, ...) {
  
  ff <- tempfile()
  png(filename = ff)
  OUT <- car::avPlots(MODEL, ...)
  dev.off()
  unlink(ff)
  OUT }

ggAVPLOTS  <- function(MODEL, YLAB = NULL, XLAB = NULL) {
  
  #Extract the information for AV plots
  AVPLOTS <- avPlots.invis(MODEL)
  K       <- length(AVPLOTS)
  
  #Create the added variable plots using ggplot
  GGPLOTS <- vector('list', K)
  for (i in 1:K) {
  DATA         <- data.frame(AVPLOTS[[i]])
  GGPLOTS[[i]] <- ggplot2::ggplot(aes_string(x = colnames(DATA)[1], 
                                             y = colnames(DATA)[2]), 
                                  data = DATA) +
                  geom_point(colour = 'blue') + 
                  geom_smooth(method = 'lm', se = FALSE, 
                              color = 'red', formula = y ~ x, linetype = 'dashed') +
                  xlab(paste0('Predictor Residual \n (', 
                         ifelse(is.null(XLAB), 
                           paste0(names(DATA)[2], ' | others'), XLAB[i]), ')')) +
                  ylab(paste0('Response Residual \n (',
                         ifelse(is.null(YLAB), 
                           paste0(names(DATA)[2], ' | others'), YLAB[i]), ')')) }
  
  #Return output object
  GGPLOTS }

log.glm = glm(Total_Species ~ NEAR_DIST_DFTrails+NEAR_STREAM, family=gaussian(link="log"), data=AllVars)
summary(log.glm)

ggAVPLOTS(log.glm, XLAB = c("Distance from Nearest Trail", "Distance from Nearest Stream"), YLAB = c("Species Count", "Species Count"))
# Change row labels
```
